let dados = [
    {
        titulo: "Grande Muralha da China",
        pais: "China",
        descricao: "A Grande Muralha da China é uma das estruturas mais icônicas e impressionantes do mundo, construída para proteger o império chinês de invasores.Se estende por mais de 20.000 km, atravessando montanhas, desertos e planícies.É Patrimônio Mundial da UNESCO e atrai milhões de turistas anualmente.",
        link: "https://pt.wikipedia.org/wiki/Muralha_da_China",
        roteiro1: "Principais pontos para um roteiro: Caminhada em Mutianyu (seção mais bem preservada);",
        roteiro2: "Visita à seção de Badaling;",
        roteiro3: "Exploração das torres de vigia;",
        roteiro4: "Observação do pôr do sol na muralha;",
        roteiro5: "Museu da Grande Muralha."
    },
    {
        titulo: "Machu Picchu",
        pais:  "Peru",
        descricao: "Machu Picchu, a 'Cidade Perdida dos Incas', é um dos destinos mais místicos e bem preservados do antigo império inca, localizado no alto das montanhas dos Andes. Este sítio arqueológico é famoso por sua arquitetura em pedra, templos, e vistas espetaculares.",
        link: "https://pt.wikipedia.org/wiki/Machu_Picchu",
        roteiro1: "Trilha Inca até Machu Picchu;",
        roteiro2: "Visita ao Templo do Sol;",
        roteiro3: "Caminhada até a montanha Huayna Picchu;",
        roteiro4: "Exploração do Templo das Três Janelas;",
        roteiro5: "Visita ao Intihuatana (relógio solar)."
    },
    {
        titulo: "Coliseu",
        pais: "Itália",
        descricao: "O Coliseu é um dos marcos mais emblemáticos de Roma e da civilização romana. Este anfiteatro antigo, que podia acomodar até 50.000 pessoas, era usado para combates de gladiadores, jogos públicos e execuções. Atualmente, é uma das Sete Maravilhas do Mundo Moderno.",
        link: "https://pt.wikipedia.org/wiki/Coliseu",
        roteiro1: "Tour pelo interior do Coliseu;", 
        roteiro2: "Visita ao subsolo do Coliseu;",
        roteiro3: "Passeio pela arena;",
        roteiro4: "Exploração dos andares superiores com vista panorâmica;",
        roteiro5: "Visita ao Arco de Constantino nas proximidades."
    },
    {
        titulo: "Torre Eiffel",
        pais: "França",
        descricao: "A Torre Eiffel, um dos monumentos mais famosos do mundo, é símbolo de Paris e da França. Construída para a Exposição Universal de 1889, a torre de ferro oferece vistas panorâmicas deslumbrantes da cidade.",
        link: "https://pt.wikipedia.org/wiki/Torre_Eiffel",
        roteiro1: "Subida aos níveis superiores da torre;",
        roteiro2: "Jantar no restaurante Le Jules Verne;", 
        roteiro3: "Passeio pelos Jardins do Champ de Mars;", 
        roteiro4: "Observação noturna da torre iluminada;",
        roteiro5: "Visita ao Trocadéro com vista para a torre."
    },
    {
        titulo: "Parque Nacional de Yellowstone",
        pais: "Estados Unidos",
        descricao: "O Parque Nacional de Yellowstone é o mais antigo parque nacional do mundo, famoso por sua vida selvagem diversificada, gêiseres e paisagens deslumbrantes. O parque é lar de fenômenos geotérmicos e oferece inúmeras oportunidades de exploração ao ar livre.",
        link: "https://pt.wikipedia.org/wiki/Parque_Nacional_de_Yellowstone",
        roteiro1: "Visita ao Gêiser Old Faithful;",
        roteiro2: "Caminhada pela Grand Prismatic Spring;",
        roteiro3: "Passeio pelo Yellowstone Canyon;",
        roteiro4: "Observação da vida selvagem (bisões, lobos e ursos);", 
        roteiro5: "Exploração da Norris Geyser Basin.",
    },
    {
        titulo: "Taj Mahal",
        pais: "Índia",
        descricao: "O Taj Mahal é um mausoléu de mármore branco construído pelo imperador Shah Jahan em memória de sua esposa Mumtaz Mahal. Considerado uma das sete maravilhas do mundo moderno, o monumento é uma obra-prima da arquitetura Mughal e símbolo do amor eterno.",
        link: "https://pt.wikipedia.org/wiki/Taj_Mahal",
        roteiro1: "Visita ao Taj Mahal ao amanhecer para ver as cores refletidas no mármore;",
        roteiro2: "Exploração dos jardins Charbagh;",
        roteiro3: "Visita ao Forte de Agra nas proximidades;",
        roteiro4: "Passeio pela cidade de Agra, com compras de artesanato local.", 
        roteiro5: "",
    },
    {
        titulo: "Grande Barreira de Corais",
        pais: "Austrália",
        descricao: "A Grande Barreira de Corais é o maior sistema de recifes de corais do mundo, localizado no nordeste da Austrália. É um paraíso para mergulhadores e entusiastas da vida marinha, com mais de 2.900 recifes e uma biodiversidade única.",
        link: "https://pt.wikipedia.org/wiki/Grande_Barreira_de_Coral",
        roteiro1: "Mergulho com snorkel para ver os corais e a vida marinha;",
        roteiro2: "Passeio de barco com fundo de vidro;",
        roteiro3: "Visita às Ilhas Whitsunday para praias paradisíacas;",
        roteiro4: "Observação de baleias e golfinhos durante as excursões marítimas.", 
        roteiro5: "",
    },
    {
        titulo: "Petra",
        pais: "Jordânia",
        descricao: "Petra é uma antiga cidade esculpida nas rochas vermelhas do deserto, famosa por sua arquitetura única. Conhecida como a 'Cidade Rosa', foi a capital do reino Nabateu e hoje é um dos locais arqueológicos mais importantes do mundo.",
        link: "https://pt.wikipedia.org/wiki/Petra",
        roteiro1: "Caminhada pelo Siq, o desfiladeiro estreito que leva à cidade;",
        roteiro2: "Visita ao Tesouro (Al-Khazneh), a fachada mais icônica de Petra;",
        roteiro3: "Exploração do Monastério (Ad-Deir), uma das maiores estruturas do local;",
        roteiro4: "Caminhada até o Alto do Sacrifício para vistas panorâmicas.", 
        roteiro5: "",
    },
    {
        titulo: "Pirâmides de Gizé",
        pais: "Egito",
        descricao: "As Pirâmides de Gizé, construídas há mais de 4.500 anos, são os monumentos mais famosos do Egito e um dos maiores feitos da engenharia humana. Localizadas nos arredores do Cairo, incluem as pirâmides de Quéops, Quéfren e Miquerinos, além da icônica Esfinge.",
        link: "https://pt.wikipedia.org/wiki/Necrópole_de_Gizé",
        roteiro1: "Visita à Grande Pirâmide de Quéops, a maior das três;",
        roteiro2: "Passeio pela Esfinge e suas misteriosas esculturas;",
        roteiro3: "Visita ao Museu Egípcio no Cairo para ver artefatos do Antigo Egito;",
        roteiro4: "Passeio de camelo ao redor das pirâmides.", 
        roteiro5: "",
    }, 
]

